language: generic

env:
    global:
        - PYTHON_VERSION=3.7
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - CONDA_CHANNELS='astropy'
        - CONDA_DEPENDENCIES='Cython scipy matplotlib shapely>=1.6 astropy-healpix'
        - PIP_DEPENDENCIES='pytest-arraydiff'
        - SETUP_XVFB=True

matrix:
    include:
        # Make sure that egg_info works without dependencies
        - env: SETUP_CMD='egg_info'

        - env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - env: SETUP_CMD='build_sphinx -w' PIP_DEPENDENCIES='sphinx-astropy'

        # Try Astropy development version
        - env: ASTROPY_VERSION=development

        # Try older numpy/astropy versions and with optional dependencies only
        - env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.12 ASTROPY_VERSION=3.0
        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.15

before_install:
    # Make sure matplotlib uses PyQT not PySide
    - export QT_API=pyqt

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then codecov; fi
