language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - CONDA_CHANNELS='conda-forge'
        - CONDA_DEPENDENCIES='Cython scipy matplotlib shapely>=1.6 healpy'
        - SETUP_XVFB=True

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Try Astropy development version
        - python: 2.7
          env: ASTROPY_VERSION=development
        - python: 3.6
          env: ASTROPY_VERSION=development

        # Try older numpy versions
        - python: 3.5
          env: NUMPY_VERSION=1.11
        - python: 3.4
          env: NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.9

        # Try without optional dependencies
        - python: 2.7
          env: PIP_DEPENDENCIES=''
        - python: 3.6
          env: PIP_DEPENDENCIES=''

before_install:
    # Make sure matplotlib uses PyQT not PySide
    - export QT_API=pyqt

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install https://github.com/astrofrog/pytest-arraydiff/archive/master.zip

script:
   - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='reproject/tests/coveragerc'; fi
