variables:
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    - linux: pep8

    - macosx: py36-test
    - macosx: py37-test

    - linux: py36-test
    - linux: py37-test

    - linux32: py36-test
    - linux32: py37-test

    - windows: py36-test
    - windows: py37-test

    - macosx: py36-docs
    - linux: py37-docs
    - macosx: py37-docs

- template: publish.yml@OpenAstronomy
  parameters:
    test_command: pytest -p no:warnings --pyargs reproject
    test_extras: test
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name : 'pypi_endpoint'
    targets:
    - sdist
    - wheels_linux
    - wheels_macosx
    - wheels_windows
