version: 2

jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_i686
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            /opt/python/cp36-cp36m/bin/pip install numpy scipy pytest-remotedata pytest-doctestplus astropy cython jinja2
            /opt/python/cp36-cp36m/bin/pip install astropy-healpix
            /opt/python/cp36-cp36m/bin/pip install https://github.com/astrofrog/pytest-arraydiff/archive/master.zip
      - run:
          name: Build
          command: |
            /opt/python/cp36-cp36m/bin/python setup.py build
      - run:
          name: Run tests    
          command: |
            /opt/python/cp36-cp36m/bin/python setup.py test

